a = int(input("Enter first numbers : "))
b = int(input("Enter second numbers : "))
print(" Addition : ", a + b)
print(" Subtraction : ", a - b)
print(" Multiplication : ", a * b)
print(" Division : ", a / b)
print(" Floor division : ", a // b )
print(" Modulo : ", a % b)
print(" Exopnential : ", a ** b)
